//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niitproject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Studentid { get; set; }
        public string Student_Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string DOB { get; set; }
    }
}
