//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class person
    {
        public int PersonID { get; set; }

        [Required(ErrorMessage = "The Name Field Is Empty")]
        public string FName { get; set; }
        
        [Required(ErrorMessage = "The Name Field Is Empty")]
        public string LName { get; set; }
       
    }
}